version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    build:
      context: .
      dockerfile: PostgreSQL/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: cicd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:

